# This updates the json file containing documentation errors every hour. 
# Based on: https://github.com/pandas-dev/pandas/blob/master/.github/workflows/ci.yml

name: update_json

# Runs the update every hour
on:
  schedule:
    - cron: '23 * * * *'

env:
  ENV_FILE: environment.yml

jobs:
  update_errors:
    runs-on: ubuntu-latest

    steps:
    
    - name: Setting conda path
      run: echo "::add-path::${HOME}/miniconda3/bin"
      
    - name: Chekout pandas-dev
      uses: actions/checkout@v2
      with:
        repository: pandas-dev/pandas
        
    - name: Setup environment and build pandas
      run: ci/setup_env.sh
      if: always()
    
    - name: Create JSON file
      run: |
        source activate pandas-dev
        python ./scripts/validate_docstrings.py --format=json > ~/pandas_docstring_errors.json
        
    - name: Chekout
      uses: actions/checkout@v2

    - name: Update JSON in repository
      run: cp -f ~/pandas_docstring_errors.json ./pandas_docstring_errors.json

    - name: Commit changes
      run: | 
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Update JSON" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

